# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Excel_Helper_names.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Excel_Helper_names(object):
    def setupUi(self, Excel_Helper_names):
        Excel_Helper_names.setObjectName("Excel_Helper_names")
        Excel_Helper_names.setEnabled(True)
        Excel_Helper_names.setFixedSize(485, 371)
        Excel_Helper_names.setBaseSize(QtCore.QSize(500, 500))
        Excel_Helper_names.setStyleSheet("background-color: rgb(23, 23, 23)")
        self.centralwidget = QtWidgets.QWidget(Excel_Helper_names)
        self.centralwidget.setObjectName("centralwidget")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(20, 20, 451, 261))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        self.textEdit.setFont(font)
        self.textEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.textEdit.setObjectName("textEdit")
        self.textEdit.setAcceptRichText(False)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 290, 451, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255, 255, 255);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(110, 320, 251, 32))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("background-color: rgb(255, 214, 149)")
        self.pushButton.setObjectName("pushButton")
        Excel_Helper_names.setCentralWidget(self.centralwidget)

        self.retranslateUi(Excel_Helper_names)
        QtCore.QMetaObject.connectSlotsByName(Excel_Helper_names)

    def retranslateUi(self, Excel_Helper_names):
        _translate = QtCore.QCoreApplication.translate
        Excel_Helper_names.setWindowTitle(_translate("Excel_Helper_names", "Excel Helper Names"))
        self.textEdit.setHtml(_translate("Excel_Helper_names", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Arial\'; font-size:18pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'.AppleSystemUIFont\'; font-size:13pt;\"><br /></p></body></html>"))
        self.label.setText(_translate("Excel_Helper_names", "Проверьте ФИО или добавьте новые"))
        self.pushButton.setText(_translate("Excel_Helper_names", "ФИО записаны верно!"))

if __name__ == "__main__":
    import sys
    import os
    os.environ["QT_AUTO_SCREEN_SCALE_FACTOR"] = "1"
    app = QtWidgets.QApplication(sys.argv)
    Excel_Helper_names = QtWidgets.QMainWindow()
    ui = Ui_Excel_Helper_names()
    ui.setupUi(Excel_Helper_names)
    Excel_Helper_names.show()
    sys.exit(app.exec_())
